Document: vscp
Title: Debian vscp Manual
Author: <insert document author here>
Abstract: This manual describes what vscp is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vscp/vscp.sgml.gz

Format: postscript
Files: /usr/share/doc/vscp/vscp.ps.gz

Format: text
Files: /usr/share/doc/vscp/vscp.text.gz

Format: HTML
Index: /usr/share/doc/vscp/html/index.html
Files: /usr/share/doc/vscp/html/*.html
